version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
      time: "04:00"
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Asia/Shanghai
